/// Calendar dimension, one row per day, 1 Jan 2025 to 30 Jun 2026. Marked as the model date table.
table Date
	lineageTag: 3d66fa89-67f3-4d75-8f0b-31b7572cf034
	dataCategory: Time

	column Date
		dataType: dateTime
		isUnique
		formatString: dd mmm yyyy
		lineageTag: 13954197-2380-423f-b894-d804dff57027
		summarizeBy: none
		sourceColumn: Date

	column Year
		dataType: int64
		lineageTag: 2a7680e7-a3dc-4fb6-9e22-c62e96c98023
		summarizeBy: none
		sourceColumn: Year

	column Quarter
		dataType: string
		lineageTag: 1ae530ba-9df1-4537-a237-a6c1d90a79b3
		summarizeBy: none
		sourceColumn: Quarter

	column 'Month Number'
		dataType: int64
		lineageTag: 19b088cd-f6d0-417d-bedf-ad9c2141f5c7
		summarizeBy: none
		sourceColumn: Month Number

	/// Month label, e.g. Jun 2026. Sorted chronologically.
	column Month
		dataType: string
		lineageTag: ef68ecf7-424b-4d49-b409-2e876f2f8779
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: YearMonth

	column YearMonth
		dataType: int64
		isHidden
		lineageTag: d91dd1df-9992-4fb6-b5f6-f4aaf12c6b45
		summarizeBy: none
		sourceColumn: YearMonth

	column 'Month Start'
		dataType: dateTime
		isHidden
		formatString: dd mmm yyyy
		lineageTag: 08bc6b85-273b-416a-b10d-84e660a124d0
		summarizeBy: none
		sourceColumn: Month Start

	column 'Week Start'
		dataType: dateTime
		formatString: dd mmm yyyy
		lineageTag: 0ccc9955-edc3-4411-ade8-104f029ce6ae
		summarizeBy: none
		sourceColumn: Week Start

	column 'Day of Week'
		dataType: string
		lineageTag: 4a8110fe-6af8-4687-9053-b20cbd9926f3
		summarizeBy: none
		sourceColumn: Day of Week
		sortByColumn: 'Day of Week Number'

	column 'Day of Week Number'
		dataType: int64
		isHidden
		lineageTag: 034905ed-b3c9-407f-b6d5-53830a93fb01
		summarizeBy: none
		sourceColumn: Day of Week Number

	partition Date = m
		mode: import
		source =
				let
				    StartDate = #date(2025, 1, 1),
				    EndDate = #date(2026, 6, 30),
				    Dates = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1, 0, 0, 0)),
				    ToTable = Table.FromList(Dates, Splitter.SplitByNothing(), {"Date"}),
				    TypedDate = Table.TransformColumnTypes(ToTable, {{"Date", type date}}),
				    AddedYear = Table.AddColumn(TypedDate, "Year", each Date.Year([Date]), Int64.Type),
				    AddedQuarter = Table.AddColumn(AddedYear, "Quarter", each "Q" & Number.ToText(Date.QuarterOfYear([Date])), type text),
				    AddedMonthNumber = Table.AddColumn(AddedQuarter, "Month Number", each Date.Month([Date]), Int64.Type),
				    AddedMonth = Table.AddColumn(AddedMonthNumber, "Month", each Date.ToText([Date], "MMM yyyy", "en-GB"), type text),
				    AddedYearMonth = Table.AddColumn(AddedMonth, "YearMonth", each Date.Year([Date]) * 100 + Date.Month([Date]), Int64.Type),
				    AddedMonthStart = Table.AddColumn(AddedYearMonth, "Month Start", each Date.StartOfMonth([Date]), type date),
				    AddedWeekStart = Table.AddColumn(AddedMonthStart, "Week Start", each Date.StartOfWeek([Date], Day.Monday), type date),
				    AddedDayOfWeek = Table.AddColumn(AddedWeekStart, "Day of Week", each Date.ToText([Date], "ddd", "en-GB"), type text),
				    AddedDayOfWeekNumber = Table.AddColumn(AddedDayOfWeek, "Day of Week Number", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type)
				in
				    AddedDayOfWeekNumber

